// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASPMVC_Practice.Models.MMAS;
using ASPMVC_Practice.Models.MMAS.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ASPMVC_Practice.Models.MMAS.Configurations
{
    public partial class _TMMasterConfiguration : IEntityTypeConfiguration<_TMMaster>
    {
        public void Configure(EntityTypeBuilder<_TMMaster> entity)
        {
            entity.HasKey(e => e.MaterialSeq)
                .HasName("PK___TMMaste__C10D1FA78A0C9F5A");

            entity.HasAnnotation("Relational:Comment", "자재데이터");

            entity.Property(e => e.MaterialSeq).HasComment("자재코드");

            entity.Property(e => e.ActionPlanSeq).HasComment("처리방안");

            entity.Property(e => e.AssetName).HasComment("품목자산분류");

            entity.Property(e => e.CustName).HasComment("고객명");

            entity.Property(e => e.ExpirationPeriod).HasComment("보관 기한");

            entity.Property(e => e.InDate).HasComment("자재 입고일");

            entity.Property(e => e.InOutDate).HasComment("LOT 대체일");

            entity.Property(e => e.InOutNo).HasComment("재고사용 수주번호");

            entity.Property(e => e.IsOutsourcing).HasComment("외주구분");

            entity.Property(e => e.ItemName).HasComment("품명");

            entity.Property(e => e.ItemNo).HasComment("품번");

            entity.Property(e => e.ItemTypeSeq).HasComment("자재군구분");

            entity.Property(e => e.LastDateTime).HasComment("최종변경일");

            entity.Property(e => e.LastUserName).HasComment("최종변경자");

            entity.Property(e => e.MaterialSpecSeq).HasComment("자재성격");

            entity.Property(e => e.MaterialTypeSeq).HasComment("ITEM구분");

            entity.Property(e => e.OrderNo).HasComment("수주번호");

            entity.Property(e => e.OrderStatusSeq).HasComment("상태");

            entity.Property(e => e.ProductName).HasComment("제품명");

            entity.Property(e => e.Qty).HasComment("수량");

            entity.Property(e => e.QtyPerBox).HasComment("박스당수량");

            entity.Property(e => e.ReInspectionDate).HasComment("장기재고 재검사일");

            entity.Property(e => e.Remark).HasComment("비고");

            entity.Property(e => e.SalesDept).HasComment("영업부서");

            entity.Property(e => e.StockOccurCauseDetail).HasComment("원인상세설명(6하원칙)");

            entity.Property(e => e.StockOccurCauseSeq).HasComment("발생요인");

            entity.Property(e => e.StockOccurDate).HasComment("재고 발생일");

            entity.Property(e => e.StockOccurDept).HasComment("귀책부서(요인기준)");

            entity.Property(e => e.StockOccurPosition).HasComment("재고발생장소");

            entity.Property(e => e.StockOccurProof).HasComment("증빙유형(기안, 메일, 기타)");

            entity.Property(e => e.StockPrice).HasComment("재고사용금액");

            entity.Property(e => e.StockQty).HasComment("재고수량");

            entity.Property(e => e.SubCategorySeq).HasComment("소분류");

            entity.Property(e => e.UnitPrice).HasComment("단가");

            entity.Property(e => e.UsedStockQty).HasComment("재고사용 수량");

            entity.Property(e => e.WHName).HasComment("위치");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_TMMaster> entity);
    }
}
