// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASPMVC_Practice.Models.MMAS;
using ASPMVC_Practice.Models.MMAS.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ASPMVC_Practice.Models.MMAS.Configurations
{
    public partial class _TMMajorConfiguration : IEntityTypeConfiguration<_TMMajor>
    {
        public void Configure(EntityTypeBuilder<_TMMajor> entity)
        {
            entity.HasKey(e => e.MajorSeq)
                .HasName("TPK_TMMajor");

            entity.HasAnnotation("Relational:Comment", "시스템 제공 기타코드 대분류");

            entity.Property(e => e.MajorSeq).HasComment("대분류코드");

            entity.Property(e => e.LastDateTime).HasComment("최종작업일시");

            entity.Property(e => e.LastUserSeq).HasComment("최종작업자");

            entity.Property(e => e.MajorName).HasComment("대분류명");

            entity.Property(e => e.Remark).HasComment("비고");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_TMMajor> entity);
    }
}
