// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASPMVC_Practice.Models.MMAS;
using ASPMVC_Practice.Models.MMAS.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ASPMVC_Practice.Models.MMAS.Configurations
{
    public partial class _TMUserConfiguration : IEntityTypeConfiguration<_TMUser>
    {
        public void Configure(EntityTypeBuilder<_TMUser> entity)
        {
            entity.HasKey(e => e.UserSeq)
                .HasName("TPK_TMEmp");

            entity.HasAnnotation("Relational:Comment", "사용자마스터");

            entity.Property(e => e.UserSeq).HasComment("사용자코드");

            entity.Property(e => e.Empid).HasComment("사번");

            entity.Property(e => e.IsAdministrator)
                .IsFixedLength()
                .HasComment("관리자여부(1 == 관리자, 0 == 일반)");

            entity.Property(e => e.IsInner)
                .IsFixedLength()
                .HasComment("재직여부(1 == 재직자, 0 == 퇴사자)");

            entity.Property(e => e.LastDateTime).HasComment("최종작업일시");

            entity.Property(e => e.LastUserSeq).HasComment("최종작업자");

            entity.Property(e => e.ResidID).HasComment("계정");

            entity.Property(e => e.UserName).HasComment("사원명");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<_TMUser> entity);
    }
}
