// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASPMVC_Practice.Models.MMAS;
using ASPMVC_Practice.Models.MMAS.dboSchema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

#nullable disable

namespace ASPMVC_Practice.Models.MMAS.Configurations
{
    public partial class SampleOrderConfiguration : IEntityTypeConfiguration<SampleOrder>
    {
        public void Configure(EntityTypeBuilder<SampleOrder> entity)
        {
            entity.HasKey(e => e.OrderID)
                .HasName("PK__SampleOr__C3905BAF5E1115A2");

            entity.Property(e => e.OrderID).ValueGeneratedNever();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SampleOrder> entity);
    }
}
