// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASPMVC_Practice.Models.MMAS;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ASPMVC_Practice.Models.MMAS
{
    public partial class MMASContext
    {
        private IMMASContextProcedures _procedures;

        public virtual IMMASContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MMASContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IMMASContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class MMASContextProcedures : IMMASContextProcedures
    {
        private readonly MMASContext _context;

        public MMASContextProcedures(MMASContext context)
        {
            _context = context;
        }
    }
}
